# Generated by Django 4.1.4 on 2023-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('channel_url', models.TextField(unique=True)),
                ('channel_name', models.TextField(unique=True)),
                ('channel_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'db_table': 'channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chen0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('com', models.TextField(blank=True, null=True)),
                ('us', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chen0',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('com', models.TextField(blank=True, null=True)),
                ('us', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chen1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('com', models.TextField(blank=True, null=True)),
                ('us', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chen2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidDate0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('load_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_date0',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidDate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('load_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_date1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidDate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('load_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_date2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelAdd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('channel_url', models.TextField(unique=True, verbose_name='Ссылка на канал')),
                ('channel_name', models.TextField(unique=True, verbose_name='Название канала')),
                ('channel_desc', models.TextField(blank=True, null=True, verbose_name='Описание канала')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
