# Generated by Django 4.1.4 on 2023-01-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('channel_url', models.TextField(unique=True)),
                ('channel_name', models.TextField(unique=True)),
                ('channel_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chen0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('com', models.TextField(blank=True, null=True)),
                ('us', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chen0',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('com', models.TextField(blank=True, null=True)),
                ('us', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chen1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('com', models.TextField(blank=True, null=True)),
                ('us', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chen2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComChenn0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chen', models.IntegerField(blank=True, null=True)),
                ('comm', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'com_chenn0',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComChenn1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chen', models.IntegerField(blank=True, null=True)),
                ('comm', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'com_chenn1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComChenn2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chen', models.IntegerField(blank=True, null=True)),
                ('comm', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'com_chenn2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data_pub', models.TextField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user_id', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('com', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_com',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidDate0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('load_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_date0',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidDate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('load_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_date1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidDate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('load_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_date2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.TextField(unique=True)),
                ('video_title', models.TextField(unique=True)),
                ('load_data', models.TextField()),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoChannelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'video_channel_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_query', models.TextField()),
                ('views', models.IntegerField()),
            ],
            options={
                'db_table': 'video_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('us', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vid_view',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
