# Generated by Django 4.1.4 on 2023-01-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeladd',
            options={'managed': False, 'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
