# Generated by Django 4.1.4 on 2023-01-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_channeladd_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channeladd',
            table='ChannelAdd',
        ),
    ]
