# Generated by Django 4.1.4 on 2023-01-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_channel_chen0_chen1_chen2_comchenn0_comchenn1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComChenn0',
        ),
        migrations.DeleteModel(
            name='ComChenn1',
        ),
        migrations.DeleteModel(
            name='ComChenn2',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='VidCom',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoChannelContent',
        ),
        migrations.DeleteModel(
            name='VideoStat',
        ),
        migrations.DeleteModel(
            name='VidUs',
        ),
        migrations.DeleteModel(
            name='VidView',
        ),
    ]
